require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GrandparentsController do

  # This should return the minimal set of attributes required to create a valid
  # Grandparent. As you add validations to Grandparent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GrandparentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all grandparents as @grandparents" do
      grandparent = Grandparent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:grandparents).should eq([grandparent])
    end
  end

  describe "GET show" do
    it "assigns the requested grandparent as @grandparent" do
      grandparent = Grandparent.create! valid_attributes
      get :show, {:id => grandparent.to_param}, valid_session
      assigns(:grandparent).should eq(grandparent)
    end
  end

  describe "GET new" do
    it "assigns a new grandparent as @grandparent" do
      get :new, {}, valid_session
      assigns(:grandparent).should be_a_new(Grandparent)
    end
  end

  describe "GET edit" do
    it "assigns the requested grandparent as @grandparent" do
      grandparent = Grandparent.create! valid_attributes
      get :edit, {:id => grandparent.to_param}, valid_session
      assigns(:grandparent).should eq(grandparent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Grandparent" do
        expect {
          post :create, {:grandparent => valid_attributes}, valid_session
        }.to change(Grandparent, :count).by(1)
      end

      it "assigns a newly created grandparent as @grandparent" do
        post :create, {:grandparent => valid_attributes}, valid_session
        assigns(:grandparent).should be_a(Grandparent)
        assigns(:grandparent).should be_persisted
      end

      it "redirects to the created grandparent" do
        post :create, {:grandparent => valid_attributes}, valid_session
        response.should redirect_to(Grandparent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grandparent as @grandparent" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grandparent.any_instance.stub(:save).and_return(false)
        post :create, {:grandparent => { "name" => "invalid value" }}, valid_session
        assigns(:grandparent).should be_a_new(Grandparent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grandparent.any_instance.stub(:save).and_return(false)
        post :create, {:grandparent => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grandparent" do
        grandparent = Grandparent.create! valid_attributes
        # Assuming there are no other grandparents in the database, this
        # specifies that the Grandparent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Grandparent.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => grandparent.to_param, :grandparent => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested grandparent as @grandparent" do
        grandparent = Grandparent.create! valid_attributes
        put :update, {:id => grandparent.to_param, :grandparent => valid_attributes}, valid_session
        assigns(:grandparent).should eq(grandparent)
      end

      it "redirects to the grandparent" do
        grandparent = Grandparent.create! valid_attributes
        put :update, {:id => grandparent.to_param, :grandparent => valid_attributes}, valid_session
        response.should redirect_to(grandparent)
      end
    end

    describe "with invalid params" do
      it "assigns the grandparent as @grandparent" do
        grandparent = Grandparent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grandparent.any_instance.stub(:save).and_return(false)
        put :update, {:id => grandparent.to_param, :grandparent => { "name" => "invalid value" }}, valid_session
        assigns(:grandparent).should eq(grandparent)
      end

      it "re-renders the 'edit' template" do
        grandparent = Grandparent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grandparent.any_instance.stub(:save).and_return(false)
        put :update, {:id => grandparent.to_param, :grandparent => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grandparent" do
      grandparent = Grandparent.create! valid_attributes
      expect {
        delete :destroy, {:id => grandparent.to_param}, valid_session
      }.to change(Grandparent, :count).by(-1)
    end

    it "redirects to the grandparents list" do
      grandparent = Grandparent.create! valid_attributes
      delete :destroy, {:id => grandparent.to_param}, valid_session
      response.should redirect_to(grandparents_url)
    end
  end

end
